# Generated by Django 3.0.2 on 2020-01-20 21:11

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.CharField(choices=[('Crema', 'crem.svg'), ('Crema_2', 'crem-2.svg'), ('Mascara_facial', 'facial-mask.svg'), ('Maquillaje', 'make_up.svg'), ('Maquillaje_1', 'makeup.svg'), ('Esèjo', 'mirror.svg'), ('Mujer', 'woman.svg')], default='woman.svg', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='sliders')),
                ('slider_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
